### ISSUE TITLE
Script focus

### ISSUE THREAD

**Issue by oxhagolli** [orensxhagolli/pyDuctor#1]
Script seems to continue playing the stream when losing focus, but doesn't take input from Leap! You have to click back on the script window to continue receiving input.

**Comment by knarfchan** [comment]
I believe the error is that the application does not receive frames if in the background by default. Perhaps a way to fix this would be to use the set_policy() function in the Controller class, which can inform the Leap Motion WebSocket server that your application wants to receive frames of tracking data even when it is in the background and not being actively used, so long as another Leap-enabled program is not in use instead. The following would be inserted
"controller.set_policy(Leap.Controller.POLICY_BACKGROUND_FRAMES)"
